local api = require("kamelbab.api")

describe("Testing", function()
	it("camel to kebab", function()
		assert.equals(api.camel_to_kebab("camelCase"), "camel-case")
		assert.equals(api.camel_to_kebab("thisIsATest"), "this-is-a-test")
		assert.equals(api.camel_to_kebab("simpleTest"), "simple-test")
	end)

	it("kebab to camel", function()
		assert.equals(api.kebab_to_camel("camel-case"), "camelCase")
		assert.equals(api.kebab_to_camel("this-is-a-test"), "thisIsATest")
		assert.equals(api.kebab_to_camel("simple-test"), "simpleTest")
	end)

	it("is kebab case", function()
		assert.equals(api.is_kebab_case("kebab-case"), true)
		assert.equals(api.is_kebab_case("kebab-Case"), false)
		assert.equals(api.is_kebab_case("kebabcase"), false)
		assert.equals(api.is_kebab_case("kebab--case"), false)
		assert.equals(api.is_kebab_case("this-is-a-kebab-case"), true)
		assert.equals(api.is_kebab_case("my-string-to-test-this-thing"), true)
	end)

	it("is camel case", function()
		assert.equals(api.is_camel_case("camelCase"), true)
		assert.equals(api.is_camel_case("CamelCase"), false)
		assert.equals(api.is_camel_case("camelcase"), false)
		assert.equals(api.is_camel_case("camelCaseTest"), true)
		assert.equals(api.is_camel_case("thisIsCamelCase"), true)
		assert.equals(api.is_camel_case("myStringToTestThisThing"), true)
	end)
end)
